version: '3.8'

services:
    mongodb:
        image: mongo
        container_name: devcamper_mongodb
        restart: always
        logging:
            driver: 'json-file'
            options:
                max-size: '10m'
                max-file: '3'
                compress: 'true'
                labels: 'mongo'
        ports:
            - 27017:27017
        volumes:
            - mongodb_data:/data/db

volumes:
    mongodb_data:
